import 'package:flutter/services.dart';

final Map<PhysicalKeyboardKey, String> keyStrings = {
  PhysicalKeyboardKey.abort: 'Abort',
  PhysicalKeyboardKey.again: 'Again',
  PhysicalKeyboardKey.altLeft: 'Left Alt',
  PhysicalKeyboardKey.altRight: 'Right Alt',
  PhysicalKeyboardKey.arrowDown: 'Arrow Down',
  PhysicalKeyboardKey.arrowLeft: 'Arrow Left',
  PhysicalKeyboardKey.arrowRight: 'Arrow Right',
  PhysicalKeyboardKey.arrowUp: 'Arrow Up',
  PhysicalKeyboardKey.audioVolumeDown: 'Volume Down',
  PhysicalKeyboardKey.audioVolumeMute: 'Volume Mute',
  PhysicalKeyboardKey.audioVolumeUp: 'Volume Up',
  PhysicalKeyboardKey.backquote: 'Backquote',
  PhysicalKeyboardKey.backslash: 'Backslash',
  PhysicalKeyboardKey.backspace: 'Backspace',
  PhysicalKeyboardKey.bassBoost: 'Bass Boost',
  PhysicalKeyboardKey.bracketLeft: 'Left Bracket',
  PhysicalKeyboardKey.bracketRight: 'Right Bracket',
  PhysicalKeyboardKey.brightnessAuto: 'Brightness Auto',
  PhysicalKeyboardKey.brightnessDown: 'Brightness Down',
  PhysicalKeyboardKey.brightnessMaximum: 'Brightness Maximum',
  PhysicalKeyboardKey.brightnessMinimum: 'Brightness Minimum',
  PhysicalKeyboardKey.brightnessToggle: 'Brightness Toggle',
  PhysicalKeyboardKey.brightnessUp: 'Brightness Up',
  PhysicalKeyboardKey.browserBack: 'Browser Back',
  PhysicalKeyboardKey.browserFavorites: 'Browser Favorites',
  PhysicalKeyboardKey.browserForward: 'Browser Forward',
  PhysicalKeyboardKey.browserHome: 'Browser Home',
  PhysicalKeyboardKey.browserRefresh: 'Browser Refresh',
  PhysicalKeyboardKey.browserSearch: 'Browser Search',
  PhysicalKeyboardKey.browserStop: 'Browser Stop',
  PhysicalKeyboardKey.capsLock: 'Caps Lock',
  PhysicalKeyboardKey.channelDown: 'Channel Down',
  PhysicalKeyboardKey.channelUp: 'Channel Up',
  PhysicalKeyboardKey.close: 'Close',
  PhysicalKeyboardKey.closedCaptionToggle: 'Closed Caption Toggle',
  PhysicalKeyboardKey.comma: 'Comma',
  PhysicalKeyboardKey.contextMenu: 'Context Menu',
  PhysicalKeyboardKey.controlLeft: 'Left Control',
  PhysicalKeyboardKey.controlRight: 'Right Control',
  PhysicalKeyboardKey.convert: 'Convert',
  PhysicalKeyboardKey.copy: 'Copy',
  PhysicalKeyboardKey.cut: 'Cut',
  PhysicalKeyboardKey.delete: 'Delete',
  PhysicalKeyboardKey.digit0: 'Digit 0',
  PhysicalKeyboardKey.digit1: 'Digit 1',
  PhysicalKeyboardKey.digit2: 'Digit 2',
  PhysicalKeyboardKey.digit3: 'Digit 3',
  PhysicalKeyboardKey.digit4: 'Digit 4',
  PhysicalKeyboardKey.digit5: 'Digit 5',
  PhysicalKeyboardKey.digit6: 'Digit 6',
  PhysicalKeyboardKey.digit7: 'Digit 7',
  PhysicalKeyboardKey.digit8: 'Digit 8',
  PhysicalKeyboardKey.digit9: 'Digit 9',
  PhysicalKeyboardKey.displayToggleIntExt: 'Display Toggle Internal/External',
  PhysicalKeyboardKey.eject: 'Eject',
  PhysicalKeyboardKey.end: 'End',
  PhysicalKeyboardKey.enter: 'Enter',
  PhysicalKeyboardKey.equal: 'Equal',
  PhysicalKeyboardKey.escape: 'Escape',
  PhysicalKeyboardKey.exit: 'Exit',
  PhysicalKeyboardKey.f1: 'F1',
  PhysicalKeyboardKey.f2: 'F2',
  PhysicalKeyboardKey.f3: 'F3',
  PhysicalKeyboardKey.f4: 'F4',
  PhysicalKeyboardKey.f5: 'F5',
  PhysicalKeyboardKey.f6: 'F6',
  PhysicalKeyboardKey.f7: 'F7',
  PhysicalKeyboardKey.f8: 'F8',
  PhysicalKeyboardKey.f9: 'F9',
  PhysicalKeyboardKey.f10: 'F10',
  PhysicalKeyboardKey.f11: 'F11',
  PhysicalKeyboardKey.f12: 'F12',
  PhysicalKeyboardKey.f13: 'F13',
  PhysicalKeyboardKey.f14: 'F14',
  PhysicalKeyboardKey.f15: 'F15',
  PhysicalKeyboardKey.f16: 'F16',
  PhysicalKeyboardKey.f17: 'F17',
  PhysicalKeyboardKey.f18: 'F18',
  PhysicalKeyboardKey.f19: 'F19',
  PhysicalKeyboardKey.f20: 'F20',
  PhysicalKeyboardKey.f21: 'F21',
  PhysicalKeyboardKey.f22: 'F22',
  PhysicalKeyboardKey.f23: 'F23',
  PhysicalKeyboardKey.f24: 'F24',
  PhysicalKeyboardKey.find: 'Find',
  PhysicalKeyboardKey.fn: 'Fn',
  PhysicalKeyboardKey.fnLock: 'Fn Lock',
  PhysicalKeyboardKey.gameButton1: 'Game Button 1',
  PhysicalKeyboardKey.gameButton2: 'Game Button 2',
  PhysicalKeyboardKey.gameButton3: 'Game Button 3',
  PhysicalKeyboardKey.gameButton4: 'Game Button 4',
  PhysicalKeyboardKey.gameButton5: 'Game Button 5',
  PhysicalKeyboardKey.gameButton6: 'Game Button 6',
  PhysicalKeyboardKey.gameButton7: 'Game Button 7',
  PhysicalKeyboardKey.gameButton8: 'Game Button 8',
  PhysicalKeyboardKey.gameButton9: 'Game Button 9',
  PhysicalKeyboardKey.gameButton10: 'Game Button 10',
  PhysicalKeyboardKey.gameButton11: 'Game Button 11',
  PhysicalKeyboardKey.gameButton12: 'Game Button 12',
  PhysicalKeyboardKey.gameButton13: 'Game Button 13',
  PhysicalKeyboardKey.gameButton14: 'Game Button 14',
  PhysicalKeyboardKey.gameButton15: 'Game Button 15',
  PhysicalKeyboardKey.gameButton16: 'Game Button 16',
  PhysicalKeyboardKey.gameButtonA: 'Game Button A',
  PhysicalKeyboardKey.gameButtonB: 'Game Button B',
  PhysicalKeyboardKey.gameButtonC: 'Game Button C',
  PhysicalKeyboardKey.gameButtonLeft1: 'Game Button Left 1',
  PhysicalKeyboardKey.gameButtonLeft2: 'Game Button Left 2',
  PhysicalKeyboardKey.gameButtonMode: 'Game Button Mode',
  PhysicalKeyboardKey.gameButtonRight1: 'Game Button Right 1',
  PhysicalKeyboardKey.gameButtonRight2: 'Game Button Right 2',
  PhysicalKeyboardKey.gameButtonSelect: 'Game Button Select',
  PhysicalKeyboardKey.gameButtonStart: 'Game Button Start',
  PhysicalKeyboardKey.gameButtonThumbLeft: 'Game Button Thumb Left',
  PhysicalKeyboardKey.gameButtonThumbRight: 'Game Button Thumb Right',
  PhysicalKeyboardKey.gameButtonX: 'Game Button X',
  PhysicalKeyboardKey.gameButtonY: 'Game Button Y',
  PhysicalKeyboardKey.gameButtonZ: 'Game Button Z',
  PhysicalKeyboardKey.help: 'Help',
  PhysicalKeyboardKey.home: 'Home',
  PhysicalKeyboardKey.hyper: 'Hyper',
  PhysicalKeyboardKey.info: 'Info',
  PhysicalKeyboardKey.insert: 'Insert',
  PhysicalKeyboardKey.intlBackslash: 'International Backslash',
  PhysicalKeyboardKey.intlRo: 'International Ro',
  PhysicalKeyboardKey.intlYen: 'International Yen',
  PhysicalKeyboardKey.kanaMode: 'Kana Mode',
  PhysicalKeyboardKey.kbdIllumDown: 'Keyboard Illumination Down',
  PhysicalKeyboardKey.kbdIllumUp: 'Keyboard Illumination Up',
  PhysicalKeyboardKey.keyA: 'Key A',
  PhysicalKeyboardKey.keyB: 'Key B',
  PhysicalKeyboardKey.keyboardLayoutSelect: 'Keyboard Layout Select',
  PhysicalKeyboardKey.keyC: 'Key C',
  PhysicalKeyboardKey.keyD: 'Key D',
  PhysicalKeyboardKey.keyE: 'Key E',
  PhysicalKeyboardKey.keyF: 'Key F',
  PhysicalKeyboardKey.keyG: 'Key G',
  PhysicalKeyboardKey.keyH: 'Key H',
  PhysicalKeyboardKey.keyI: 'Key I',
  PhysicalKeyboardKey.keyJ: 'Key J',
  PhysicalKeyboardKey.keyK: 'Key K',
  PhysicalKeyboardKey.keyL: 'Key L',
  PhysicalKeyboardKey.keyM: 'Key M',
  PhysicalKeyboardKey.keyN: 'Key N',
  PhysicalKeyboardKey.keyO: 'Key O',
  PhysicalKeyboardKey.keyP: 'Key P',
  PhysicalKeyboardKey.keyQ: 'Key Q',
  PhysicalKeyboardKey.keyR: 'Key R',
  PhysicalKeyboardKey.keyS: 'Key S',
  PhysicalKeyboardKey.keyT: 'Key T',
  PhysicalKeyboardKey.keyU: 'Key U',
  PhysicalKeyboardKey.keyV: 'Key V',
  PhysicalKeyboardKey.keyW: 'Key W',
  PhysicalKeyboardKey.keyX: 'Key X',
  PhysicalKeyboardKey.keyY: 'Key Y',
  PhysicalKeyboardKey.keyZ: 'Key Z',
  PhysicalKeyboardKey.lang1: 'Language 1',
  PhysicalKeyboardKey.lang2: 'Language 2',
  PhysicalKeyboardKey.lang3: 'Language 3',
  PhysicalKeyboardKey.lang4: 'Language 4',
  PhysicalKeyboardKey.lang5: 'Language 5',
  PhysicalKeyboardKey.launchApp1: 'Launch App 1',
  PhysicalKeyboardKey.launchApp2: 'Launch App 2',
  PhysicalKeyboardKey.launchAssistant: 'Launch Assistant',
  PhysicalKeyboardKey.launchAudioBrowser: 'Launch Audio Browser',
  PhysicalKeyboardKey.launchCalendar: 'Launch Calendar',
  PhysicalKeyboardKey.launchContacts: 'Launch Contacts',
  PhysicalKeyboardKey.launchControlPanel: 'Launch Control Panel',
  PhysicalKeyboardKey.launchDocuments: 'Launch Documents',
  PhysicalKeyboardKey.launchInternetBrowser: 'Launch Internet Browser',
  PhysicalKeyboardKey.launchKeyboardLayout: 'Launch Keyboard Layout',
  PhysicalKeyboardKey.launchMail: 'Launch Mail',
  PhysicalKeyboardKey.launchPhone: 'Launch Phone',
  PhysicalKeyboardKey.launchScreenSaver: 'Launch Screen Saver',
  PhysicalKeyboardKey.launchSpreadsheet: 'Launch Spreadsheet',
  PhysicalKeyboardKey.launchWordProcessor: 'Launch Word Processor',
  PhysicalKeyboardKey.lockScreen: 'Lock Screen',
  PhysicalKeyboardKey.logOff: 'Log Off',
  PhysicalKeyboardKey.mailForward: 'Mail Forward',
  PhysicalKeyboardKey.mailReply: 'Mail Reply',
  PhysicalKeyboardKey.mailSend: 'Mail Send',
  PhysicalKeyboardKey.mediaFastForward: 'Media Fast Forward',
  PhysicalKeyboardKey.mediaLast: 'Media Last',
  PhysicalKeyboardKey.mediaPause: 'Media Pause',
  PhysicalKeyboardKey.mediaPlay: 'Media Play',
  PhysicalKeyboardKey.mediaPlayPause: 'Media Play/Pause',
  PhysicalKeyboardKey.mediaRecord: 'Media Record',
  PhysicalKeyboardKey.mediaRewind: 'Media Rewind',
  PhysicalKeyboardKey.mediaSelect: 'Media Select',
  PhysicalKeyboardKey.mediaStop: 'Media Stop',
  PhysicalKeyboardKey.mediaTrackNext: 'Media Track Next',
  PhysicalKeyboardKey.mediaTrackPrevious: 'Media Track Previous',
  PhysicalKeyboardKey.metaLeft: 'Left Meta',
  PhysicalKeyboardKey.metaRight: 'Right Meta',
  PhysicalKeyboardKey.microphoneMuteToggle: 'Microphone Mute Toggle',
  PhysicalKeyboardKey.minus: 'Minus',
  PhysicalKeyboardKey.newKey: 'New',
  PhysicalKeyboardKey.nonConvert: 'Non-Convert',
  PhysicalKeyboardKey.numLock: 'Num Lock',
  PhysicalKeyboardKey.numpad0: 'Numpad 0',
  PhysicalKeyboardKey.numpad1: 'Numpad 1',
  PhysicalKeyboardKey.numpad2: 'Numpad 2',
  PhysicalKeyboardKey.numpad3: 'Numpad 3',
  PhysicalKeyboardKey.numpad4: 'Numpad 4',
  PhysicalKeyboardKey.numpad5: 'Numpad 5',
  PhysicalKeyboardKey.numpad6: 'Numpad 6',
  PhysicalKeyboardKey.numpad7: 'Numpad 7',
  PhysicalKeyboardKey.numpad8: 'Numpad 8',
  PhysicalKeyboardKey.numpad9: 'Numpad 9',
  PhysicalKeyboardKey.numpadAdd: 'Numpad Add',
  PhysicalKeyboardKey.numpadBackspace: 'Numpad Backspace',
  PhysicalKeyboardKey.numpadClear: 'Numpad Clear',
  PhysicalKeyboardKey.numpadClearEntry: 'Numpad Clear Entry',
  PhysicalKeyboardKey.numpadComma: 'Numpad Comma',
  PhysicalKeyboardKey.numpadDecimal: 'Numpad Decimal',
  PhysicalKeyboardKey.numpadDivide: 'Numpad Divide',
  PhysicalKeyboardKey.numpadEnter: 'Numpad Enter',
  PhysicalKeyboardKey.numpadEqual: 'Numpad Equal',
  PhysicalKeyboardKey.numpadMemoryAdd: 'Numpad Memory Add',
  PhysicalKeyboardKey.numpadMemoryClear: 'Numpad Memory Clear',
  PhysicalKeyboardKey.numpadMemoryRecall: 'Numpad Memory Recall',
  PhysicalKeyboardKey.numpadMemoryStore: 'Numpad Memory Store',
  PhysicalKeyboardKey.numpadMemorySubtract: 'Numpad Memory Subtract',
  PhysicalKeyboardKey.numpadMultiply: 'Numpad Multiply',
  PhysicalKeyboardKey.numpadParenLeft: 'Numpad Parenthesis Left',
  PhysicalKeyboardKey.numpadParenRight: 'Numpad Parenthesis Right',
  PhysicalKeyboardKey.numpadSignChange: 'Numpad Sign Change',
  PhysicalKeyboardKey.numpadSubtract: 'Numpad Subtract',
  PhysicalKeyboardKey.open: 'Open',
  PhysicalKeyboardKey.pageDown: 'Page Down',
  PhysicalKeyboardKey.pageUp: 'Page Up',
  PhysicalKeyboardKey.paste: 'Paste',
  PhysicalKeyboardKey.pause: 'Pause',
  PhysicalKeyboardKey.period: 'Period',
  PhysicalKeyboardKey.power: 'Power',
  PhysicalKeyboardKey.print: 'Print',
  PhysicalKeyboardKey.printScreen: 'Print Screen',
  PhysicalKeyboardKey.privacyScreenToggle: 'Privacy Screen Toggle',
  PhysicalKeyboardKey.programGuide: 'Program Guide',
  PhysicalKeyboardKey.props: 'Props',
  PhysicalKeyboardKey.quote: 'Quote',
  PhysicalKeyboardKey.redo: 'Redo',
  PhysicalKeyboardKey.resume: 'Resume',
  PhysicalKeyboardKey.save: 'Save',
  PhysicalKeyboardKey.scrollLock: 'Scroll Lock',
  PhysicalKeyboardKey.select: 'Select',
  PhysicalKeyboardKey.selectTask: 'Select Task',
  PhysicalKeyboardKey.semicolon: 'Semicolon',
  PhysicalKeyboardKey.shiftLeft: 'Left Shift',
  PhysicalKeyboardKey.shiftRight: 'Right Shift',
  PhysicalKeyboardKey.showAllWindows: 'Show All Windows',
  PhysicalKeyboardKey.slash: 'Slash',
  PhysicalKeyboardKey.sleep: 'Sleep',
  PhysicalKeyboardKey.space: 'Space',
  PhysicalKeyboardKey.speechInputToggle: 'Speech Input Toggle',
  PhysicalKeyboardKey.spellCheck: 'Spell Check',
  PhysicalKeyboardKey.superKey: 'Super Key',
  PhysicalKeyboardKey.suspend: 'Suspend',
  PhysicalKeyboardKey.tab: 'Tab',
  PhysicalKeyboardKey.turbo: 'Turbo',
  PhysicalKeyboardKey.undo: 'Undo',
  PhysicalKeyboardKey.usbErrorRollOver: 'USB Error Rollover',
  PhysicalKeyboardKey.usbErrorUndefined: 'USB Error Undefined',
  PhysicalKeyboardKey.usbPostFail: 'USB Post Fail',
  PhysicalKeyboardKey.usbReserved: 'USB Reserved',
  PhysicalKeyboardKey.wakeUp: 'Wake Up',
  PhysicalKeyboardKey.zoomIn: 'Zoom In',
  PhysicalKeyboardKey.zoomOut: 'Zoom Out',
  PhysicalKeyboardKey.zoomToggle: 'Zoom Toggle',
};

String? getKeyLabel(PhysicalKeyboardKey key) {
  return keyStrings[key];
}